pipeline {
    agent any
    stages {
        stage('Maven Validate') {
             steps {
                echo 'Maven Validate .....'
            }
        }
        stage('Maven Compile') {
             steps {
                echo 'Maven Compile .....'
            }
        }

        stage('Maven Test') {
             steps {
                echo 'Maven Test .....'
            }
        }

        stage('Maven Build') {
             steps {
                echo 'Maven Build .....'
            }
        }

        stage('Docker Build') {
             steps {
                echo 'Build Docker Image .....'
            }
        }

        stage('Docker Deploy') {
             steps {
                echo 'Build Docker Image .....'
            }
        }

        stage('Docker Publish') {
             steps {
                echo 'Build Docker Image .....'
            }
        }
    }
}